dist: xenial
addons:
  apt:
    packages:
      - rabbitmq-server
services:
  - rabbitmq
language: python
python:
  - '2.7'
  - '3.6'
  - '3.7'
  - '3.8'
install:
  - pip install -U tox
script: tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
cache:
  directories:
    - $HOME/.cache/pip
deploy:
  provider: pypi
  user: zephor5
  password:
    secure: MF4/A+5Fecy9uuEttFKxQm7IIUULS+BgCji0oy7vyeRdcZvu7IrvgSVhz6nMOCw7ljcFLnQcQMb2M7Zau+6G29XJv1iR6YjXM+tWIBUysgm3DaY6QOXlxd4etI4ixYPTjeRSe7mWv3ZA+ziEg/4s/R/P50g+IFfqtBOTZoRgzWfskKqSa7UWLz8QCeBu4kET3T6EYSz4Xkpte1suMt81VVeLBMfNMcTM0lGUyjaDO3apojYWrusnupfAmBP5fB89Wun05fyPmkvNU5xVW1Ff4iC1zNPYWjJhiT/AR7DOxjbqwWZ9DDoDyGuzSy6hL9t1sF8vw/pTHPf0gXxalHS0NUIkSXgKvyFuWGIUOmayFoT44MXwaja1Wv7ZFWehq79mzcvmaAoB5GtzQXSQKy0m2gXh08uJ0MrLKHrtI4cSAtqWczAz4kzJxnwXZwNc69TuSqphOFTwk9YCekFXG2lkaMJwXw1Q1chM5x0urqNZp18YJfLhbl5lPhvXqm80dWpxMOD7hlxG1i/tBHj9NrKz6HOt+RC3OKpsmgk8a8Km8hHAK9LmAWKjkqP9Nn4GyngbMgvqjE9LVVMLwFx3NIRL2V3+1KzIfwR1w2nkMsp3l6kVre3W0OVq/c9CHgWI+v3V4OcVWTiBSp8ClUkI3dfKnGxAbf4oFMG1POTerwpS2I0=
  on:
    tags: true
