language: python
python:
  - '2.7'
install:
  - pip install -U tox
script: tox
cache:
  directories:
    - $HOME/.cache/pip
deploy:
  provider: pypi
  user: zephor5
  password:
    secure: TNTQ/ZdP7ygaJTKdNop+KOqGXRghchl/8UUH5tM5P+fnFxrGBitVvWYlurhhHphjRWFXify0k4uCU3D14OIRTyPAKtC5wBqWCwV+hWx2C0T332ou8lowczvN/uEWLNnoJKiiS2127QBLUHEoFR2/LKdchCvVY7n4gnYzjkCnXin45/CdOV88065xAriO4/UG11Q2ohMTmP5Vm6z51102aPySTqwPQJB5ywg3Q7uUs2CZjQIa7IUV7ZXe/lGe0bs5jF24A1i6Vrdt5PykRuTdIsjsvvcnD4ghHpB5XOlev5OFWaXyCqAvjfZySjYaD6Tv1EJbGDZb/sTxps/7CRixCkJX7CDY6a2krMRxdq38zGnFjRN5/R9Fb5fbjQnrGgJusi0oLbNuzm1tSb37rdddYqK79iWBEUSt+nnu5LZL3FlPz6cxld8kBQId7juZ+aFY/Y6bThSB7WIVgouY8gW7t9NKDGisGrc0xYk38dH6EblYKbOQ/J4eYMqmrmgcGm71S2b4q5jOA+PJF/7NLUP7wmYyqi/6WficFsV4DDzd1wPHs7yBMwPXpNvgpPJ74iNiFIdI+HzL6LblMmTBm0EB+8Q6iYwK3GVJulrQwW5H5xaIABJNnOgMU5fQcGT5N76jbP2xHu79ZgBFzhE4fiNAlnSKnCN+qfX4TmEz09A8P1g=
  on:
    tags: true

